# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nikita Katilis
author: Nikita Katilis
email: nikitakatilis@gmail.com
description: >-
  Game Audio Designer
baseurl: ""
url: "https://nikitakatilisaudio.dev"

favicon: "favicon.ico"

permalink: /:slug/

remote_theme: Katalize/katalize_jakyll_theme
theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

social:
  name: Nikita Katilis
  links:
    - https://www.instagram.com/katalizeaudio/

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-compose
  - jekyll-sitemap
  - jekyll-youtube
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE

header_pages:
  - index.md
  - showreel.md
  - implementation.md
  - cv.md
  - music.md
  - content.md
  - contact.md

style: dark

footer: 'nikitakatilis@gmail.com / 2024 

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - vendor/bundle/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
